---
# Defines the metadata for the Helm chart.
apiVersion: v2
# Sets the name of the chart.
name: setup
# Provides a short description of the chart's purpose.
description: A chart to deploy project-specific K8s resources.
# Specifies that this is an application chart.
type: application
# Sets the version of the chart itself.
version: 0.1.0
# Sets the version of the application deployed by this chart.
appVersion: 0.1.0
