---
# Specifies the API version for the External Secrets Operator.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  # Sets the name of the cluster-wide secret store.
  name: vault-backend
spec:
  # Configures the Vault provider settings.
  provider:
    vault:
      # Sets the internal Kubernetes DNS address for the Vault service.
      server: "http://vault.vault.svc.cluster.local:8200"

      # Specifies the mount path of the KV secrets engine in Vault.
      path: "secret"

      # Specifies the version of the KV secrets engine.
      version: "v2"

      # Configures the authentication method for Vault.
      auth:
        kubernetes:
          # Sets the mount path where the Kubernetes auth method is enabled in Vault.
          mountPath: "kubernetes"

          # Specifies the Vault Role to assume during authentication.
          role: "secret-reader"
