---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-es
spec:
  # Reference the ClusterSecretStore we created in the setup chart
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  # How often to check Vault for updates
  refreshInterval: "1m"

  # The native K8s secret to create
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner

  # The data to fetch from Vault
  data:
    - secretKey: SECRET_USERNAME  # Key in K8s Secret / Env Var
      remoteRef:
        key: {{ .Values.secret.vaultPath }}
        property: username  # Key inside Vault JSON

    - secretKey: SECRET_MESSAGE
      remoteRef:
        key: {{ .Values.secret.vaultPath }}
        property: message
