---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Sets a unique name for the ExternalSecret resource.
  name: {{ .Chart.Name }}-es
spec:
  # References the ClusterSecretStore created by the setup chart.
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  # Sets the interval for checking updates in Vault.
  refreshInterval: "1m"

  # Defines the target Kubernetes Secret to be created.
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner

  # Maps Vault secret data to Kubernetes Secret keys.
  data:
    - secretKey: SECRET_USERNAME
      remoteRef:
        key: {{ .Values.secret.vaultPath }}
        property: username

    - secretKey: SECRET_MESSAGE
      remoteRef:
        key: {{ .Values.secret.vaultPath }}
        property: message
